/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package retroact;

public class App {
    public String getGreeting() {
        return "Use the REPL to load swing-react and then call run-app. Read README.md.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
